project:
  type: website
  output-dir: docs

website:
  title: "Hanna Kim"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme: flatly
    css: styles.css
    page-layout: full

editor: visual

